name: material_search_bar
description: Material search bar with circular reveal animation like whatsapp as flutter widget
version: 1.0.1
homepage: https://github.com/kishandonga/material_search_bar

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  circular_reveal_animation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
